version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - '3000:80'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
