{
 "title": "FastAPI Monitoring Dashboard",
 "tags": [
  "fastapi",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Resident Memory Usage (in Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes\n",
     "legendFormat": "{{job}} - Memory Usage"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Request Errors (500)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code='500'}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status Code",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"2..\"}[5m])) by (status)\n\n",
     "legendFormat": "HTTP {{status_code}} Success"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) by (status)\n",
     "legendFormat": "HTTP {{status_code}} Error"
    }
   ]
  },
  {
   "title": "CPU Usage (rate per 5 minutes)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}} - CPU Usage"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}